#!/usr/bin/env python
'''	Parse data from primary.py (raw data is number of occurrences of candidate names per journal)
	Open each data file (csv) generated by primary.py as data_sets.
	Sort data into journal-dependent timelines and query-dependent averages (all journals per query)
	Plot using matplotlib
'''
import subprocess
import matplotlib as mpl
mpl.use('TkAgg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
from matplotlib import gridspec as gs
mpl.rc('figure',facecolor='white')

def journal_timelines_maker(journal_timelines,this_data):
	for row in this_data:
		row_nums = [float(x) for x in row[1:]]
		if sum(row_nums):												#avoid division by zero if zero name occurrences
			row_nums = [int(1000.*x/sum(row_nums))/10. for x in row_nums]		
		if not len(journal_timelines[row[0]]):			
			journal_timelines[row[0]] = np.array([row_nums])							#not populated, initialize array			
		else:
			journal_timelines[row[0]] = np.vstack([journal_timelines[row[0]],row_nums])	#found populated, stack new row
	return journal_timelines

#-----plot journal_timelines-----#
def graph_journal_timelines(journal_timelines,num_files):
	#-----place hashtag before names to hide their data-----#
	show_names = '''
			#clinton,
			sanders,
			trump,
			#cruz,
			#kasich'''
	#type = 'plot'
	type='scatter'
	colors = 'red green blue yellow orange'.split(' ')
	name_map = [1 if x and x[0] != '#' else 0 for x in show_names.replace('\n','').replace('\t','').split(',') ]
	color_map = 'red green blue yellow orange'.split(' ')	
	plot_names = ' vs. '.join([x for x in show_names.replace('\n','').replace('\t','').split(',') if x and x[0] != '#'])
	
	for journal in journal_timelines.iterkeys():	
		for i in range(5):
			if name_map[i]:
				eval('plt.'+type+'(range(num_files),journal_timelines[journal][:,'+str(i)+'],color=\''+str(color_map[i])+'\',alpha=.15,label=\''+plot_names[i]+'\')')

	label_color='blue'
	plt.title(plot_names+':\n % name occurrence (for 5 current candidates) in all journals',color=label_color)
	plt.xlabel('query number (from March 24, 2016)',fontsize=14,color=label_color)
	plt.ylabel('% name each journal',fontsize=14,color=label_color)
	ax = plt.subplot()
	ax.set_axis_bgcolor('white')
	plt.tight_layout()
	plt.show()

#-----main-----#
def main():
	#open relevant files and append each data-set to data_sets
	files = subprocess.Popen(['ls data'],stdout=subprocess.PIPE,shell=True).communicate()[0].split('\n')
	files = [x for x in files if x[:4] == 'dat2']
	num_files = len(files)
	data_sets = []
	for file in files:	
		with open('data/'+file,'r') as f:
			data_sets.append(f.read())	
	
	#-----definitions-----#
	curr_cand = 'clinton sanders trump cruz kasich'.split(' ')
	with open('news_sites.txt','r') as f:
		journals = f.read().split('\n')[::2]
	journal_timelines = {journal:np.array([]) for journal in journals}
	coll_totals = []
	raw_totals = []
	coll_percents = []
	
	for data in data_sets:
			#parse each data set
		this_data = np.array([x.split(',')[0:6] for x in data.split('\n')[1:-2]])	
			#add each data set to journal-dependent timeline
		journal_timelines = journal_timelines_maker(journal_timelines,this_data)
			#remove journal label and convert to integer matrix
		this_data = this_data[:,1:].astype('i1')					
		single_coll_total = [sum(this_data[:,x]) for x in range(len(curr_cand))]
		coll_totals.append(single_coll_total)				#total mentions for each candidate in all journals per query
		
		#graph journal-dependent data
	graph_journal_timelines(journal_timelines,num_files)
	
	for i in coll_totals:
		all_cand_sum = sum(i)
		coll_percents.append([int(1000.*x/all_cand_sum)/10. for x in i])
	coll_percents = np.array(coll_percents)

	avg_percents = [int(10*sum(coll_percents[:,x])/num_files)/10. for x in range(5)]
	print np.array(avg_percents),'(avg)'
	
	#----------------------start plotting averages---------------------------#
	fig = plt.figure()
	ax = fig.add_subplot(111)
	ax1=fig.add_subplot(211)
	ax2=fig.add_subplot(212)
	
	for i in range(4):
		ax.spines['top bottom left right'.split(' ')[i]].set_color('none')
	ax.tick_params(labelcolor='w', top='off', bottom='off', left='off', right='off')
	
	color_map = 'blue,green,red,cyan,magenta'.split(',')
	
	coll_totals = np.array(coll_totals)
	for cand in range(len(curr_cand)):
		ax1.plot(range(len(files)),coll_percents[:,cand],label=curr_cand[cand])		
		ax2.plot(range(len(files)),coll_totals[:,cand],label=curr_cand[cand])
	
	box = ax1.get_position()
	ax1.set_position([box.x0, box.y0, box.width * 0.8, box.height])
	box = ax2.get_position()
	ax2.set_position([box.x0, box.y0, box.width * 0.8, box.height])

	#----legend----#
	ax1.legend(loc='top left', bbox_to_anchor=(1, 1),fontsize=12,numpoints=1)
	#-----titles and labels-----#
	font_size = 12
	ax1.set_title('avg. percent appearances',fontsize=font_size)
	ax1.set_ylabel('avg. percent')
	ax2.set_title('raw totals from collected data',fontsize=font_size)
	ax2.set_ylabel('raw numbers')
	plt.xlabel('query number, March 24, 2016 - present')
	#plt.tight_layout()
	plt.show()

if __name__ == '__main__':
	main()